name: system_info
description: 'A new Flutter plugin project.'
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  pigeon: ^22.4.1

flutter:
  plugin:
    platforms:
      android:
        package: com.example.system_info
        pluginClass: SystemInfoPlugin
      ios:
        pluginClass: SystemInfoPlugin
